language: python
dist: xenial

python:
    - 3.6

before_install:
    - python -m pip install --upgrade pip
    - sudo apt-get install -y autodock-vina


install:
    - pip install -r requirements.txt

scripts:
    - python regression-test.py

