dist xenial
sudo:true

language: python    
python:
  - "3.6"
  - "3.7"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get python3-setuptools python3-pip

install:
  - pip3 install --user -r requirements.txt

