language: python
dist: xenial

matrix:
  include:
    - python:  3.6
      env:  NUMPY=1.15.4


before_install:
    - pip uninstall --yes numpy
    - pip uninstall --yes numpy
    - python -m pip install --upgrade pip
    - pip uninstall --yes numpy
    - sudo apt-get install -y autodock-vina


install:
    - pip install -r requirements.txt

script:
    - python regression-test.py

